### ISSUE TITLE
Fout antwoord

### ISSUE THREAD

**Issue by JenteTib** [SamuelDerous/deepfaked#6]
Bij de vraag "welke van de onderstaande is een complottheorie"  is de maanlanding van 1969 aangeduid als fout met reden 'er is voldoende bewijs' maar dat geldt toch ook voor aids, die wel wordt gezien als complottheorie.

**Comment by SamuelDerous** [comment]
Dag Jente, super dat je nadenkt over de vragen... Ik probeer de logica van de antwoorden uit te leggen. De complottheorie is niet dat AIDS bestaat, maar dat het zou gemaakt zijn in een laboratorium om de lagere klassen mee uit te roeien. Zo is er b.v. ook het idee dat de maanlanding in 1969 nooit heeft plaats gevonden, terwijl natuurlijk enkel de mensen die er ook daadwerkelijk bij waren met absolute zekerheid kunnen zeggen dat die heeft plaatsgevonden, wordt toch wel aangenomen dat die ook echt heeft plaatsgevonden.

**Comment by SamuelDerous** [comment]
Ik ga kijken of ik de antwoorden wat duidelijker kan verwoorden.
